channels:
- conda-forge
- defaults
dependencies:
- _libgcc_mutex
- _pytorch_select
- aiofiles
- aiosqlite
- argon2-cffi
- argon2-cffi-bindings
- asttokens
- attrs
- beautifulsoup4
- blas
- bleach
- brotli-python
- ca-certificates
- certifi
- cffi
- cryptography
- cudatoolkit
- cyrus-sasl
- decorator
- defusedxml
- entrypoints
- exceptiongroup
- executing
- expat
- fontconfig
- freetype
- glib
- gst-plugins-base
- gstreamer
- icu
- idna
- importlib_metadata
- importlib_resources
- intel-openmp
- ipython
- ipython_genutils
- jedi
- jinja2
- jpeg
- jsonschema
- jsonschema-specifications
- jupyter
- jupyter_client
- jupyter_console
- jupyter_core
- jupyter_events
- jupyter_server
- jupyter_server_fileid
- jupyter_server_ydoc
- jupyter_ydoc
- jupyterlab_pygments
- jupyterlab_server
- jupyterlab_widgets
- krb5
- libclang13
- libffi
- libgomp
- libllvm14
- libmklml
- libpng
- libpq
- libsodium
- libxcb
- libxml2
- lz4-c
- matplotlib-inline
- mistune
- mkl
- mkl-service
- mkl_fft
- mkl_random
- mysql
- nb_conda
- nb_conda_kernels
- nbclassic
- nbconvert
- nbformat
- nest-asyncio
- ninja
- ninja-base
- notebook-shim
- openssl
- packaging
- pandocfilters
- parso
- pcre
- pickleshare
- pip
- pkgutil-resolve-name
- platformdirs
- ply
- prometheus_client
- prompt_toolkit
- ptyprocess
- pure_eval
- pycparser
- pygments
- pyopenssl
- pyqt
- pyqt5-sip
- pysocks
- python
- python-dateutil
- python-fastjsonschema
- python-json-logger
- python_abi
- pytz
- pyyaml
- qt-main
- qtpy
- referencing
- requests
- rfc3339-validator
- rfc3986-validator
- send2trash
- setuptools
- sip
- six
- sniffio
- soupsieve
- sqlite
- stack_data
- terminado
- tinycss2
- tk
- tomli
- typing_extensions
- wcwidth
- webencodings
- websocket-client
- wheel
- xz
- y-py
- yaml
- ypy-websocket
- zeromq
- zipp
- zlib
- zstd
- pip:
  - absl-py==2.0.0
  - accelerate==0.27.0
  - anyio==4.1.0
  - arrow==1.3.0
  - astunparse==1.6.3
  - async-lru==2.0.4
  - babel==2.13.1
  - cachetools==5.3.2
  - charset-normalizer==3.3.2
  - comm==0.2.0
  - contourpy==1.2.0
  - cycler==0.12.1
  - debugpy==1.8.0
  - diffusers==0.27.0.dev0
  - et-xmlfile==1.1.0
  - filelock==3.13.1
  - flatbuffers==23.5.26
  - fonttools==4.46.0
  - fqdn==1.5.1
  - freetype-py==2.4.0
  - fsspec==2023.10.0
  - gast==0.5.4
  - google-auth==2.24.0
  - google-auth-oauthlib==1.1.0
  - google-pasta==0.2.0
  - grpcio==1.59.3
  - h5py==3.10.0
  - huggingface-hub==0.20.3
  - imageio==2.33.1
  - importlib-metadata==6.8.0
  - invisible-watermark==0.2.0
  - ipydatawidgets==4.3.5
  - ipykernel==6.27.1
  - ipywidgets==8.1.1
  - isoduration==20.11.0
  - joblib==1.3.2
  - json5==0.9.14
  - jsonpointer==2.4
  - jupyter-client==8.6.0
  - jupyter-console==6.6.3
  - jupyter-events==0.9.0
  - jupyter-lsp==2.2.1
  - jupyter-server==2.11.1
  - jupyter-server-terminals==0.4.4
  - jupyterlab==4.0.9
  - jupyterlab-server==2.25.2
  - keras==2.15.0
  - kiwisolver==1.4.5
  - libclang==16.0.6
  - markdown==3.5.1
  - markupsafe==2.1.3
  - matplotlib==3.8.2
  - ml-dtypes==0.2.0
  - mouseinfo==0.1.3
  - mpmath==1.3.0
  - munch==4.0.0
  - nbclient==0.9.0
  - networkx==3.2.1
  - notebook==7.0.6
  - numpy==1.26.2
  - nvidia-cublas-cu12==12.1.3.1
  - nvidia-cuda-cupti-cu12==12.1.105
  - nvidia-cuda-nvrtc-cu12==12.1.105
  - nvidia-cuda-runtime-cu12==12.1.105
  - nvidia-cudnn-cu12==8.9.2.26
  - nvidia-cufft-cu12==11.0.2.54
  - nvidia-curand-cu12==10.3.2.106
  - nvidia-cusolver-cu12==11.4.5.107
  - nvidia-cusparse-cu12==12.1.0.106
  - nvidia-nccl-cu12==2.18.1
  - nvidia-nvjitlink-cu12==12.3.101
  - nvidia-nvtx-cu12==12.1.105
  - oauthlib==3.2.2
  - opencv-python==4.8.1.78
  - openpyxl==3.1.2
  - opt-einsum==3.3.0
  - overrides==7.4.0
  - pandas==2.1.3
  - pexpect==4.9.0
  - pillow==10.1.0
  - prompt-toolkit==3.0.41
  - protobuf==4.23.4
  - psutil==5.9.6
  - pyasn1==0.5.1
  - pyasn1-modules==0.3.0
  - pyautogui==0.9.54
  - pygetwindow==0.0.9
  - pyglet==2.0.10
  - pymsgbox==1.0.9
  - pyopengl==3.1.0
  - pyparsing==3.1.1
  - pyperclip==1.8.2
  - pyrect==0.2.0
  - pyrender==0.1.45
  - pyscreeze==0.1.30
  - python3-xlib==0.15
  - pythreejs==2.4.2
  - pytweening==1.0.7
  - pywavefront==1.3.3
  - pywavelets==1.5.0
  - pyzmq==24.0.1
  - qtconsole==5.5.1
  - regex==2023.12.25
  - requests-oauthlib==1.3.1
  - rpds-py==0.13.1
  - rsa==4.9
  - safetensors==0.4.2
  - scikit-learn==1.3.2
  - scipy==1.11.4
  - seaborn==0.13.0
  - stack-data==0.6.3
  - sympy==1.12
  - tensorboard==2.15.1
  - tensorboard-data-server==0.7.2
  - tensorboard-logger==0.1.0
  - tensorflow==2.15.0
  - tensorflow-estimator==2.15.0
  - tensorflow-io-gcs-filesystem==0.34.0
  - termcolor==2.3.0
  - threadpoolctl==3.2.0
  - tokenizers==0.15.1
  - torch==2.1.1+cu118
  - torchaudio==2.1.1+cu118
  - torchvision==0.16.1+cu118
  - tornado==6.4
  - tqdm==4.66.1
  - traitlets==5.9.0
  - traittypes==0.2.1
  - transformers==4.37.2
  - trimesh==4.0.5
  - triton==2.1.0
  - types-python-dateutil==2.8.19.14
  - typing-extensions==4.8.0
  - tzdata==2023.3
  - uri-template==1.3.0
  - urllib3==2.1.0
  - webcolors==1.13
  - werkzeug==3.0.1
  - widgetsnbextension==4.0.9
  - wrapt==1.14.1
  - xgboost==2.0.3
name: ismail_env
